authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout')
]

babadu/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('authentication/', include('authentication.urls')),
    path('event/', include('event.urls')),
    path('hasil-pertandingan/', include('hasil_pertandingan.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('tes-kualifikasi/', include('tes_kualifikasi.urls')),
    path('atlet/', include('atlet.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('pertandingan/', include('pertandingan.urls')),
]

base/urls.py
from django.urls import path
from base.views import *

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

authentication/forms.py
from django import forms

class LoginForm(forms.Form):
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'login-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'login-email', 'placeholder': 'Email'}))


class RegisterAtletForm(forms.Form):
    PLAY_CHOICES = [
        (False, 'Left'),
        (True, 'Right'),
    ]
    KELAMIN_CHOICES = [
        (True, 'Laki-laki'),
        (False, 'Perempuan'),
    ]
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'register-atlet-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'register-atlet-email', 'placeholder': 'Email'}))
    negara = forms.CharField(
        label='negara',
        min_length=5,
        max_length=25,
        widget=forms.TextInput(
            attrs={'id': 'register-atlet-negara', 'placeholder': 'Negara'})
    )
    tanggal_lahir = forms.DateField(
        label='register-pelatih-tanggal-mulai',
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    play = forms.CharField(
        label='play',
        widget=forms.RadioSelect(
            choices=PLAY_CHOICES
        )
    )
    tinggi_badan = forms.IntegerField(
        min_value=1,
        max_value=200,
        widget=forms.NumberInput(
            attrs={'id': 'register-atlet-tinggi-badan', 'placeholder': 'Tinggi badam'})
    )
    jenis_kelamin = forms.CharField(
        label='jenis kelamin',
        widget=forms.RadioSelect(
            choices=KELAMIN_CHOICES
        )
    )


class RegisterPelatihForm(forms.Form):
    KATEGORI_CHOICES = [
        ('tunggal putra', 'tunggal putra'),
        ('tunggal putri', 'tunggal putri'),
        ('ganda putra', 'ganda putra'),
        ('ganda putri', 'ganda putri'),
        ('ganda campuran', 'ganda campuran'),
    ]
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'register-pelatih-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'register-pelatih-email', 'placeholder': 'Email'}))
    kategori = forms.MultipleChoiceField(
        label='register-pelatih-kategori',
        widget=forms.CheckboxSelectMultiple,
        choices=KATEGORI_CHOICES)
    tanggal_mulai = forms.DateField(
        label='register-pelatih-tanggal-mulai',
        widget=forms.DateInput(attrs={'type': 'date'})
    )


class RegisterUmpireForm(forms.Form):
    nama = forms.CharField(
        label='nama',
        min_length=5,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'register-umpire-nama', 'placeholder': 'Nama'})
    )
    email = forms.CharField(label='email', widget=forms.TextInput(
        attrs={'id': 'register-umpire-email', 'placeholder': 'Email'}))
    negara = forms.CharField(
        label='negara',
        min_length=5,
        max_length=25,
        widget=forms.TextInput(
            attrs={'id': 'register-umpire-negara', 'placeholder': 'Negara'})
    )

authentication/views.py
import datetime
import re
import uuid
from django.shortcuts import render, redirect
from django.db import connection, InternalError
from django.contrib import messages
from base.helper.function import parse
from authentication.forms import *
from authentication.constant import *
from authentication.query import *
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login(request):
    if request.method == 'POST':
        nama = request.POST.get('nama')
        email = request.POST.get('email')
        query = get_user_query(nama, email)
        cursor = connection.cursor()
        cursor.execute("set search_path to babadu;")
        cursor.execute(query)
        res = parse(cursor)
        request.session['is_atlet'] = False
        request.session['is_pelatih'] = False
        request.session['is_umpire'] = False
        if len(res) == 1:
            mem = res[0]
            for attr in mem:
                if isinstance(mem[attr], uuid.UUID):
                    request.session[attr] = str(mem[attr])
                elif isinstance(mem[attr], datetime.date):
                    date = datetime.datetime.strptime(str(mem[attr]), '%Y-%m-%d')
                    formatted_date = date.strftime('%d %B %Y')
                    request.session[attr] = formatted_date
                else:
                    request.session[attr] = mem[attr]
            request.session[SESSION_ROLE_KEYS[mem['member_type']]] = True
            return redirect('/dashboard')     
        else:
            messages.info(request,'Username atau Password salah')

    context = {'login_form': LoginForm()}
    return render(request, 'login.html', context)

@csrf_exempt
def register(request):
    if request.method == 'POST':
        if 'atlet_submit' in request.POST:
            atlet_form = RegisterAtletForm(request.POST)
            print(atlet_form.errors)
            if atlet_form.is_valid():
                nama = atlet_form.cleaned_data['nama']
                email = atlet_form.cleaned_data['email']
                negara = atlet_form.cleaned_data['negara']
                tanggal_lahir = atlet_form.cleaned_data['tanggal_lahir']
                play = atlet_form.cleaned_data['play']
                tinggi_badan = atlet_form.cleaned_data['tinggi_badan']
                jenis_kelamin = atlet_form.cleaned_data['jenis_kelamin']
                payload = atlet_register(nama, email, negara, tanggal_lahir, play, tinggi_badan, jenis_kelamin)
                if payload['success']:
                    return redirect('authentication:login')
                else:
                    trimmed_string = re.sub(r'\(|\)|\'', '', payload['msg'])
                    message = re.search(r'\[([^]]+)\]', trimmed_string).group(1)
                    messages.info(request, message)
        elif 'pelatih_submit' in request.POST:
            pelatih_form = RegisterPelatihForm(request.POST)
            if pelatih_form.is_valid():
                nama = pelatih_form.cleaned_data['nama']
                email = pelatih_form.cleaned_data['email']
                kategori = pelatih_form.cleaned_data['kategori']
                tanggal_mulai = pelatih_form.cleaned_data['tanggal_mulai']
                payload = pelatih_register(nama, email, kategori, tanggal_mulai)
                if payload['success']:
                    return redirect('authentication:login')
                else:
                    trimmed_string = re.sub(r'\(|\)|\'', '', payload['msg'])
                    message = re.search(r'\[([^]]+)\]', trimmed_string).group(1)
                    messages.info(request, message)
        elif 'umpire_submit' in request.POST:
            umpire_form = RegisterUmpireForm(request.POST)
            if umpire_form.is_valid():
                print('run 2')
                nama = umpire_form.cleaned_data['nama']
                email = umpire_form.cleaned_data['email']
                negara = umpire_form.cleaned_data['negara']
                print(nama)
                payload = umpire_register(nama, email, negara)
                if payload['success']:
                    return redirect('authentication:login')
                else:
                    trimmed_string = re.sub(r'\(|\)|\'', '', payload['msg'])
                    message = re.search(r'\[([^]]+)\]', trimmed_string).group(1)
                    messages.info(request, message)
    context = {
        'atlet_form': RegisterAtletForm(),
        'pelatih_form': RegisterPelatihForm(),
        'umpire_form': RegisterUmpireForm(),
    }
    return render(request, 'register.html', context)


def atlet_register(nama, email, negara, tanggal_lahir, play, tinggi_badan, jenis_kelamin):
    try:
        id = uuid.uuid4()
        cursor = connection.cursor()
        cursor.execute("set search_path to babadu;")
        mem_query = insert_member_query(id, nama, email)
        cursor.execute(mem_query)
        atlet_query = insert_atlet_query(id, tanggal_lahir, negara, play, tinggi_badan, jenis_kelamin)
        cursor.execute(atlet_query)
    except InternalError as e:
        return {
            'success': False,
            'msg': str(e.args)
        }
    else:
        return {
            'success': True,
        }
    
def pelatih_register(nama, email, kategori, tanggal_mulai):
    try:
        id = uuid.uuid4()
        cursor = connection.cursor()
        cursor.execute("set search_path to babadu;")
        mem_query = insert_member_query(id, nama, email)
        cursor.execute(mem_query)
        pelaih_qeury = insert_pelatih_query(id, tanggal_mulai)
        cursor.execute(pelaih_qeury)
        for k in kategori:
            print(k)
            spesialisasi_kategori_query = insert_pelatih_spesialisasi_query(id, k)
            cursor.execute(spesialisasi_kategori_query)
    except InternalError as e:
        return {
            'success': False,
            'msg': str(e.args)
        }
    else:
        return {
            'success': True,
        }

def umpire_register(nama, email, negara):
    try:
        id = uuid.uuid4()
        cursor = connection.cursor()
        cursor.execute("set search_path to babadu;")
        mem_query = insert_member_query(id, nama, email)
        cursor.execute(mem_query)
        umpire_query = insert_umpire_query(id, negara)
        cursor.execute(umpire_query)
    except InternalError as e:
        return {
            'success': False,
            'msg': str(e.args)
        }
    else:
        return {
            'success': True,
        }

def logout(request):
    if "id" in request.session:
        request.session.clear()
        request.session['is_atlet'] = False
        request.session['is_pelatih'] = False
        request.session['is_umpire'] = False
        return redirect('/')
    return redirect('/')

authentication/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load filter %}

{% block meta %}
<title>Babadu | Login</title>
{% endblock meta %}

{% block content %}

<section id="authentication-login" class="h-screen w-full xl:px-20 lg:px-10 sm:px-2 px-4 py-16 text-white">
    <div class="h-full flex flex-col items-center justify-center">
        <section id="b01" class="w-full">
            <div class="max-w-md mx-auto p-4 border border-shark-400 rounded-lg">
                <div class="flex flex-row items-center justify-start gap-4">
                    <div class="font-semibold text-lg p-4 bg-primary-500 rounded-md">
                        B01
                    </div>
                    <div class="text-start text-shark-400">
                        <a href="/">
                            <span class="text-white font-semibold hover:text-primary-500 transition cursor-pointer">Babadu.b01</span>
                        </a>
                        dibuat untuk memenuhi tugas kelompok pada mata kuliah Basis Data.
                    </div>
                </div>
            </div>
        </section>
        <div class="w-full md:w-4/6 my-6 mx-auto h-auto p-4 border border-shark-500 rounded-lg">
            <form method="POST" action="" class="w-full flex flex-col gap-4">
                <div class="text-2xl font-semibold text-primary-400 text-center">
                    Login Form
                </div>
                <hr class="border-shark-400">
                {% csrf_token %}
                <section id="auth-login-input" class="space-y-2">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Nama
                        </div>
                        <div>
                            {{ login_form.nama|addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Email
                        </div>
                        <div>
                            {{ login_form.email|addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                </section>
                <section id="auth-login-submit" class="space-y-1 mt-2">
                    <button
                        class="bg-primary-500 w-full py-2 rounded-lg hover:bg-primary-400 transition cursor-pointer text-white font-semibold"
                        type="submit" value="Login">
                        Login
                    </button>
                    <div class="grid grid-cols-9 items-center text-shark-400">
                        <hr class="border-shark-400 col-span-4">
                        <div class="text-xs text-center col-span-1">
                            Atau
                        </div>
                        <hr class="border-shark-400 col-span-4">
                    </div>
                    <h1 class="text-shark-200 text-base text-center">Belum terdaftar sebagai member Babadu?
                        <a class="text-primary-400 hover:underline transition" href="{% url 'authentication:register' %}">
                            Buat membership
                        </a>
                    </h1>
                </section>
            </form>
        </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <section class="flex justify-center items-center overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none bg-neutral-800/70">
        <div class="relative w-full md:w-4/6 lg:w-3/6 xl:w-2/5 my-6 mx-auto h-full lg:h-auto md:h-auto">
            <div class="translate h-full lg:h-auto md:h-auto border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-midnight outline-none focus:outline-none">
                <div class="px-8 py-12 flex flex-col gap-4">
                    <div class="text-2xl text-center font-semibold">
                        Login Failed
                    </div>
                    <hr class="border-shark-400 w-full">
                    <div class="text-center text-danger">
                        {{ message }}
                    </div>
                    <hr class="border-shark-400 w-full">
                    <div>
                        <h1 class="text-shark-200 text-base text-center">
                            Ingin mencoba login dengan email yang telah terdafar? 
                            <a class="text-primary-400 hover:underline transition"
                                href="{% url 'authentication:login' %}">
                                Login lagi
                            </a>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
    {% endif %}
</section>

{% endblock content %}