atlet/urls.py
from django.urls import path
from atlet.views import *

app_name = 'atlet'

urlpatterns = [
    path('daftar/', daftar_atlet_view, name='daftar'),
    path('lihat/', pelatih_lihat_atlet_view, name='lihat'),
    path('umpire-daftar-atlet', umpire_daftar_atlet_view, name='umpire-daftar-atlet')
]

babadu/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('authentication/', include('authentication.urls')),
    path('event/', include('event.urls')),
    path('hasil-pertandingan/', include('hasil_pertandingan.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('tes-kualifikasi/', include('tes_kualifikasi.urls')),
    path('atlet/', include('atlet.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('pertandingan/', include('pertandingan.urls')),
]

base/urls.py
from django.urls import path
from base.views import *

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import *

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard_view, name='main'),
]

event/urls.py
from django.urls import path
from event.views import *

app_name = 'event'

urlpatterns = [
    path('lihat/', lihat_event_view, name='lihat'),
    path('daftar/', daftar_stadium_view, name='daftar'),
    path('daftar/<slug:stadium>/', daftar_event_view, name='daftar-event'),
    path('daftar/<slug:stadium>/<slug:event>/<int:tahun>', daftar_partai_kompetisi, name='daftar-partai-kompetisi'),
    path('lihat/enrolled-partai-kompetisi-event', enrolled_partai_kompetisi_event_view, name='lihat-enrolled-partai-kompetisi-event'),
    path('lihat/enrolled-event', enrolled_event_view, name='lihat-enrolled-event')
]

sponsor/urls.py
from django.urls import path
from sponsor.views import *

app_name = 'sponsor'

urlpatterns = [
    path('daftar-sponsor/', daftar_sponsor_view, name='daftar-sponsor'),
    path('list-sponsor/', list_sponsor_view, name='list-sponsor'),
] 

base/views.py
from django.shortcuts import render, redirect

def main(request):
    if "id" in request.session:
        return redirect('dashboard:main')
    return render(request, 'index.html')

base/templates/base.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        primary: {
                            '50': '#f2fcf1',
                            '100': '#dff9df',
                            '200': '#b5f0b6',
                            '300': '#8ee790',
                            '400': '#56d25a',
                            '500': '#2fb833',
                            '600': '#219825',
                            '700': '#1e7721',
                            '800': '#1c5f20',
                            '900': '#194e1c',
                            '950': '#082b0b',
                        },
                        shark: {
                            '50': '#f6f6f7',
                            '100': '#e2e3e5',
                            '200': '#c5c6ca',
                            '300': '#a0a0a8',
                            '400': '#7b7c86',
                            '500': '#61616b',
                            '600': '#4c4c55',
                            '700': '#3f4046',
                            '800': '#35353a',
                            '900': '#27272a',
                            '950': '#18181b',
                        },
                        midnight: '#18181b',
                        danger: '#ff2643',

                    }
                },
            }
        }
    </script>
    {% block meta %}
    {% endblock meta %}
</head>

<body class="bg-midnight">
    {% include 'navbar.html' %}
    <section id="body-wrapper" class="max-w-7xl mx-auto">
        {% block content %}
        {% endblock content %}
    </section>
</body>

</html>

base/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Babadu | B01</title>
{% endblock meta %}

{% block content %}

<section id="authentication" class="h-screen w-full xl:px-20 lg:px-10 sm:px-2 px-4">
    <div class="h-full flex flex-col gap-8 items-center justify-center text-white text-center">
        <section id="b01" class="w-full">
            <div class="max-w-md mx-auto p-4 border border-shark-900 rounded-lg">
                <div class="flex flex-row items-center justify-start gap-4">
                    <div class="font-semibold text-lg p-4 bg-primary-500 rounded-md">
                        B01
                    </div>
                    <div class="text-start text-shark-400">
                        <span class="text-white font-semibold">Babadu.b01</span>
                        dibuat untuk memenuhi tugas kelompok pada mata kuliah Basis Data.
                    </div>
                </div>
            </div>
        </section>
        <section id="header" class="space-y-2">
            <div class="text-white font-semibold space-y-2">
                <div class="text-5xl">Babadu</div>
                <div class="text-2xl">Badan Badminton Dunie</div>
            </div>
            <div class="text-xl text-shark-400 max-w-md">
                Organisasi yang menaungi pertandingan utama badminton di level internasional
            </div>
        </section>
        <section id="buttons" class="w-full">
            <div class="max-w-lg mx-auto text-white text-lg font-semibold">
                <a href="{% url 'authentication:login' %}">
                    <button
                        class="bg-primary-500 w-full py-2 rounded-lg hover:bg-primary-400 transition cursor-pointer">
                        Login
                    </button>
                </a>
                <div class="grid grid-cols-7 items-center text-shark-400 my-2">
                    <hr class="border-shark-400 col-span-3">
                    <div class="text-xs col-span-1">
                        Atau
                    </div>
                    <hr class="border-shark-400 col-span-3">
                </div>
                <a href="{% url 'authentication:register' %}">
                    <button
                        class="bg-primary-500 w-full py-2 rounded-lg hover:bg-primary-400 transition cursor-pointer">
                        Register
                    </button>
                </a>
            </div>
        </section>
        <section class="h-4" />
    </div>
</section>

{% endblock content %}

base/templates/navbar.html
<nav class="fixed w-full z-10 border-b border-shark-900 bg-midnight">
    <div class="max-w-6xl mx-auto py-4">
        <div class="flex flex-row justify-between items-center xl:px-20 lg:px-10 sm:px-2 px-4">
            <a href="/">
                <section id="logo" class="font-semibold text-xl text-white flex flex-row space-x-4">
                    <svg fill="#000000" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
                        class="w-6 h-6 fill-white" viewBox="0 0 466.35 466.35"
                        xml:space="preserve">
                        <g>
                            <path d="M445.99,335.173l-33.065-33.065l-15.935,15.936L239.902,0h-14.307l-38.27,38.271l-1.384,75.715l-68.43-6.5l-10.026,10.027
                                l6.501,68.428l-75.717,1.384L0,225.595V239.9l318.042,157.09l-15.935,15.934l33.065,33.066c27.146,27.146,71.159,27.146,98.305,0
                                l12.511-12.512C473.137,406.332,473.137,362.32,445.99,335.173z M307.079,207.356l-15.627,15.627l-40.521-53.653l25.013-25.012
                                L307.079,207.356z M268.894,245.54l-23.352,23.353l-53.653-40.521l36.483-36.484L268.894,245.54z M218.684,51.596l7.672-7.672
                                l34.813,70.484l-29.465,29.464l-14.359-19.012L218.684,51.596z M194.093,146.499l15.053,19.932l-42.714,42.714L146.5,194.092
                                l-4.996-52.589L194.093,146.499z M114.407,261.168l-70.483-34.813l7.673-7.672l73.264-1.338l19.013,14.359L114.407,261.168z
                                M207.358,307.076l-63.04-31.135l25.014-25.013l53.652,40.522L207.358,307.076z M237.268,321.851l11.174-11.173l63.877,48.243
                                L237.268,321.851z M270.999,288.119l17.121-17.121l52.831,69.951L270.999,288.119z M310.679,248.439l11.173-11.173l37.07,75.05
                                L310.679,248.439z"/>
                        </g>
                    </svg>
                    <div>
                        Babadu
                    </div>
                </section>
            </a>
            <section id="navbar-menus" class="flex flex-row gap-6 text-shark-400">
                {% if request.session.is_atlet or request.session.is_pelatih or request.session.is_umpire %}
                <div class="cursor-pointer hover:text-primary-400 transition">
                    <a href="{% url 'dashboard:main' %}">
                        <button class="navbar-menu dashboard">
                            Dashboard
                        </button>
                    </a>
                </div>
                {% endif %}
                {% if request.session.is_atlet %}
                <div>
                    <button class="relative peer hover:text-primary-400">Ujian Kualifikasi</button>
                    <div class="absolute hidden peer-hover:flex hover:flex flex-col bg-midnight border border-shark-900 rounded-lg">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'tes-kualifikasi:atlet-list-ujian-kualifikasi' %}">
                            <button class="">
                                List Ujian Kualifikasi
                            </button>
                        </a>
                        <hr class="border-shark-900">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'tes-kualifikasi:atlet-riwayat-ujian-kualifikasi' %}">
                            <button>
                                Riwayat Ujian Kualifikasi
                            </button>
                        </a>
                    </div>
                </div>
                {% if request.session.is_terkualifikasi %}
                <div>
                    <button class="relative peer hover:text-primary-400">Event</button>
                    <div class="absolute hidden peer-hover:flex hover:flex flex-col bg-midnight border border-shark-900 rounded-lg">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'event:daftar' %}">
                            <button>
                                Daftar Event
                            </button>
                        </a>
                        <hr class="border-shark-900">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'event:lihat-enrolled-event' %}">
                            <button>
                                Enrolled Event
                            </button>
                        </a>
                        <hr class="border-shark-900">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'event:lihat-enrolled-partai-kompetisi-event' %}">
                            <button>
                                Enrolled Partai Kompetisi Event
                            </button>
                        </a>
                    </div>
                </div>
                <div>
                    <button class="relative peer hover:text-primary-400">Sponsor</button>
                    <div class="absolute hidden peer-hover:flex hover:flex flex-col bg-midnight border border-shark-900 rounded-lg">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'sponsor:daftar-sponsor' %}">
                            <button>
                                Daftar Sponsor
                            </button>
                        </a>
                        <hr class="border-shark-900">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'sponsor:list-sponsor' %}">
                            <button>
                                List Sponsor
                            </button>
                        </a>
                    </div>
                </div>
                {% endif %}
                {% endif %}
                {% if request.session.is_pelatih %}
                <div>
                    <button class="relative peer hover:text-primary-400">Latih Atlet</button>
                    <div class="absolute hidden peer-hover:flex hover:flex flex-col bg-midnight border border-shark-900 rounded-lg">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'atlet:daftar' %}">
                            <button class="">
                                Create Latih Atlet
                            </button>
                        </a>
                        <hr class="border-shark-900">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'atlet:lihat' %}">
                            <button>
                                List Atlet Dilatih
                            </button>
                        </a>
                    </div>
                </div>
                {% endif %}
                {% if request.session.is_umpire %}
                <div>
                    <button class="relative peer hover:text-primary-400">Atlet</button>
                    <div class="absolute hidden peer-hover:flex hover:flex flex-col bg-midnight border border-shark-900 rounded-lg">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'atlet:umpire-daftar-atlet' %}">
                            <button class="">
                                Daftar Atlet
                            </button>
                        </a>
                        <hr class="border-shark-900">
                    </div>
                </div>
                <div>
                    <button class="relative peer hover:text-primary-400">Ujian Kualifikasi</button>
                    <div class="absolute hidden peer-hover:flex hover:flex flex-col bg-midnight border border-shark-900 rounded-lg">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'tes-kualifikasi:buat-ujian-kualifikasi' %}">
                            <button class="">
                                Buat Ujian Kualifikasi
                            </button>
                        </a>
                        <hr class="border-shark-900">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'tes-kualifikasi:umpire-list-ujian-kualifikasi' %}">
                            <button>
                                List Ujian Kualifikasi
                            </button>
                        </a>
                        <hr class="border-shark-900">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'tes-kualifikasi:umpire-riwayat-ujian-kualifikasi' %}">
                            <button>
                                Riwayat Ujian Kualifikasi
                            </button>
                        </a>
                    </div>
                </div>
                <div>
                    <button class="relative peer hover:text-primary-400">Event</button>
                    <div class="absolute hidden peer-hover:flex hover:flex flex-col bg-midnight border border-shark-900 rounded-lg">
                        <a class="px-5 py-3 hover:text-primary-400" href="{% url 'pertandingan:lihat-partai-kompetisi' %}">
                            <button class="">
                                List Partai Kompetisi
                            </button>
                        </a>
                    </div>
                </div>
                {% endif %}   
                {% if request.session.is_atlet or request.session.is_pelatih or request.session.is_umpire %}
                <div class="cursor-pointer hover:text-danger transition">
                    <a href="{% url 'authentication:logout' %}" class="navbar-menu">
                        Logout
                    </a>
                </div>
                {% endif %}
            </section>
        </div>
    </div>
</nav>

<script>
    $(document).ready(function () {
        const regexExp = /^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$/gi;
        var currentPath = window.location.pathname.split('/');
        currentPath = currentPath.pop() || currentPath.pop();
        console.log(currentPath);
        $('.navbar-menu').removeClass('text-primary-500');
        $(`.${currentPath}`).addClass('text-primary-500');
    });
</script>