babadu/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('authentication/', include('authentication.urls')),
    path('event/', include('event.urls')),
    path('hasil-pertandingan/', include('hasil_pertandingan.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('tes-kualifikasi/', include('tes_kualifikasi.urls')),
    path('atlet/', include('atlet.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('pertandingan/', include('pertandingan.urls')),
]

base/urls.py
from django.urls import path
from base.views import *

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
]

tes_kualifikasi/urls.py
from django.urls import path
from tes_kualifikasi.views import *

app_name = 'tes-kualifikasi'

urlpatterns = [
    path('buat-ujian-kualifikasi/', buat_ujian_kualifikasi_view, name='buat-ujian-kualifikasi'),
    path('umpire-list-ujian-kualifikasi/', umpire_list_ujian_kualifikasi_view, name='umpire-list-ujian-kualifikasi'),
    path('atlet-list-ujian-kualifikasi/', atlet_list_ujian_kualifikasi_view, name='atlet-list-ujian-kualifikasi'),
    path('atlet-list-ujian-kualifikasi/<int:tahun>/<int:batch>/<slug:tempat>/<slug:tanggal>/', pertanyaan_kualifikasi_view, name='pertanyaan-kualifikasi'),
    path('umpire-riwayat-ujian-kualifikasi/', umpire_riwayat_ujian_kualifikasi_view, name='umpire-riwayat-ujian-kualifikasi'),
    path('atlet-riwayat-ujian-kualifikasi/', atlet_riwayat_ujian_kualifikasi_view, name='atlet-riwayat-ujian-kualifikasi')
]

tes_kualifikasi/forms.py
from django import forms

class BuatUjianKualifikasi(forms.Form):
    tahun = forms.CharField(
        label='tahun',
        min_length=1,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'tahun', 'placeholder': 'YYYY'})
    )
    batch = forms.CharField(
        label='batch',
        min_length=1,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'batch', 'placeholder': 'Nomor Batch'})
    )
    tempat_pelaksanaan = forms.CharField(
        label='tempat pelaksanaan',
        min_length=1,
        max_length=150,
        widget=forms.TextInput(
            attrs={'id': 'tempat-pelaksanaan', 'placeholder': 'Tempat Pelaksanaan'})
    )
    tanggal_pelaksanaan = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

class PertanyaanKualifikasiForm(forms.Form):
    PILIHAN_NOMOR_SATU = [
        ('0', 'China'),
        ('20', 'Britain'),
        ('0', 'Denmark'),
    ]
    nomor_satu = forms.CharField(
        label='satu',
        widget=forms.RadioSelect(
            choices=PILIHAN_NOMOR_SATU
        )
    )
    PILIHAN_NOMOR_DUA = [
        ('0', '11'),
        ('0', '16'),
        ('20', '21'),
    ]
    nomor_dua = forms.CharField(
        label='dua',
        widget=forms.RadioSelect(
            choices=PILIHAN_NOMOR_DUA
        )
    )
    PILIHAN_NOMOR_TIGA = [
        ('20', 'Badminton World Federation – BWF'),
        ('0', 'International Badminton Association – IBA'),
        ('0', 'Badminton World Organization – BWO'),
    ]
    nomor_tiga = forms.CharField(
        label='tiga',
        widget=forms.RadioSelect(
            choices=PILIHAN_NOMOR_TIGA
        )
    )
    PILIHAN_NOMOR_EMPAT = [
        ('0', 'Before the game starts'),
        ('0', 'After the game finishes'),
        ('20', 'After the rally finishes'),
    ]
    nomor_empat = forms.CharField(
        label='empat',
        widget=forms.RadioSelect(
            choices=PILIHAN_NOMOR_EMPAT
        )
    )
    PILIHAN_NOMOR_LIMA = [
        ('0', 'Error'),
        ('20', 'Fault'),
        ('0', 'Mistake'),
    ]
    nomor_lima = forms.CharField(
        label='lima',
        widget=forms.RadioSelect(
            choices=PILIHAN_NOMOR_LIMA
        )
    )

tes_kualifikasi/views.py
from django.shortcuts import render, redirect
from tes_kualifikasi.forms import *
from tes_kualifikasi.query import *
from django.db import connection, InternalError
from base.helper.function import parse
from tes_kualifikasi.helper import *
from django.contrib import messages
import datetime
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def buat_ujian_kualifikasi_view(request):
    if "id" not in request.session or not request.session['is_umpire']:
        return redirect('main:main')
    
    cursor = connection.cursor()
    form = BuatUjianKualifikasi()
    
    if request.method == 'POST' and 'buat_ujian_kualifikasi_submit' in request.POST:
        tahun = request.POST.get('tahun')
        batch = request.POST.get('batch')
        tempat_pelaksanaan = request.POST.get('tempat_pelaksanaan')
        tanggal_pelaksanaan = request.POST.get('tanggal_pelaksanaan')
        query = insert_ujian_kualifikasi_query(tahun, batch, tempat_pelaksanaan, tanggal_pelaksanaan)
        cursor.execute("set search_path to babadu;")
        cursor.execute(query)
        return redirect('tes-kualifikasi:umpire-list-ujian-kualifikasi')
    
    context = {
        'buat_ujian_kualifikasi': form,
    }

    return render(request, 'buat_ujian_kualifikasi.html', context)

def umpire_list_ujian_kualifikasi_view(request):
    if "id" not in request.session or not request.session['is_umpire']:
        return redirect('main:main')
    
    query = get_list_ujian_kualifikasi_query()
    cursor = connection.cursor()
    cursor.execute("set search_path to babadu;")
    cursor.execute(query)
    res = parse(cursor)
    context = {'list_ujian_kualifikasi': res}
    return render(request, 'list_ujian_kualifikasi.html', context)

def atlet_list_ujian_kualifikasi_view(request):
    if "id" not in request.session or not request.session['is_atlet']:
        return redirect('main:main')
    
    query = get_list_ujian_kualifikasi_query()
    cursor = connection.cursor()
    cursor.execute("set search_path to babadu;")
    cursor.execute(query)
    res = parse(cursor)
    list_ujian_kualifikasi = []
    for item in res:
        item['tempat_url'] = convert_to_slug(item['tempat'])
        for attr in item:
            if isinstance(item[attr], datetime.date):
                date = datetime.datetime.strptime(str(item[attr]), '%Y-%m-%d')
                formatted_date = date.strftime('%d %B %Y')
                item[attr] = formatted_date
        item['tanggal_url'] = convert_to_slug(item['tanggal'])
        list_ujian_kualifikasi.append(item)

    context = {'list_ujian_kualifikasi': list_ujian_kualifikasi}

    return render(request, 'list_ujian_kualifikasi.html', context)

@csrf_exempt
def pertanyaan_kualifikasi_view(request, tahun, batch, tempat, tanggal):
    if "id" not in request.session or not request.session['is_atlet']:
        return redirect('main:main')

    tempat = convert_to_title(tempat)
    tanggal = convert_to_date(tanggal)

    cursor = connection.cursor()
    cursor.execute("set search_path to babadu;")
    form = PertanyaanKualifikasiForm()
    
    if request.method == 'POST' and 'pertanyaan_kualifikasi_submit' in request.POST:
        nomor_satu = request.POST.get('nomor_satu')
        nomor_dua = request.POST.get('nomor_dua')
        nomor_tiga = request.POST.get('nomor_tiga')
        nomor_empat = request.POST.get('nomor_empat')
        nomor_lima = request.POST.get('nomor_lima')
        hasil_ujian = int(nomor_satu) + int(nomor_dua) + int(nomor_tiga) + int(nomor_empat) + int(nomor_lima)
        hasil_lulus = False
        if hasil_ujian >= 80:
            hasil_lulus = True
        payload = insert_atlet_nonkualifikasi_ujian_kualifikasi_view(request.session['id'], tahun, batch, tempat, tanggal, hasil_lulus)
        if payload['success']:
            return redirect('tes-kualifikasi:atlet-riwayat-ujian-kualifikasi')
        else:
            messages.info(request, 'Anda tidak dapat mengikuti ujian kualifikasi ini.')
    
    context = {
        'pertanyaan_kualifikasi': form,
    }

    return render(request, 'pertanyaan_kualifikasi.html', context)

def insert_atlet_nonkualifikasi_ujian_kualifikasi_view(id_atlet, tahun, batch, tempat, tanggal, hasil_lulus):
    try:
        cursor = connection.cursor()
        cursor.execute("set search_path to babadu;")
        query = insert_atlet_nonkualifikasi_ujian_kualifikasi_query(id_atlet, tahun, batch, tempat, tanggal, hasil_lulus)
        cursor.execute(query)
    except InternalError as e:
        return {
            'success': False,
        }
    else:
        return {
            'success': True,
        }

def umpire_riwayat_ujian_kualifikasi_view(request):
    if "id" not in request.session or not request.session['is_umpire']:
        return redirect('main:main')
    
    query = umpire_get_riwayat_ujian_kualifikasi_query()
    cursor = connection.cursor()
    cursor.execute("set search_path to babadu;")
    cursor.execute(query)
    res = parse(cursor)
    context = {'riwayat_ujian_kualifikasi': res}
    return render(request, 'riwayat_ujian_kualifikasi.html', context)

def atlet_riwayat_ujian_kualifikasi_view(request):
    if "id" not in request.session or not request.session['is_atlet']:
        return redirect('main:main')
    
    query = atlet_get_riwayat_ujian_kualifikasi_query(request.session['id'])
    cursor = connection.cursor()
    cursor.execute("set search_path to babadu;")
    cursor.execute(query)
    res = parse(cursor)
    context = {'riwayat_ujian_kualifikasi': res}
    return render(request, 'riwayat_ujian_kualifikasi.html', context)

tes_kualifikasi/templates/buat_ujian_kualifikasi.html
{% extends 'base.html' %}
{% load static %}
{% load filter %}

{% block meta %}
<title>Babadu | Tes Kualifikasi</title>
{% endblock meta %}

{% block content %}

<section id="authentication" class="h-screen w-full xl:px-20 lg:px-10 sm:px-2 px-4">
    <div class="h-full flex flex-col gap-8 items-center justify-center text-white">
        <section id="b01" class="w-full">
            <div class="max-w-md mx-auto p-4 border border-shark-400 rounded-lg">
                <div class="flex flex-row items-center justify-start gap-4">
                    <div class="font-semibold text-lg p-4 bg-primary-500 rounded-md">
                        B01
                    </div>
                    <div class="text-start text-shark-400">
                        <a href="/">
                            <span
                                class="text-white font-semibold hover:text-primary-500 transition cursor-pointer">Babadu.b01</span>
                        </a>
                        dibuat untuk memenuhi tugas kelompok pada mata kuliah Basis Data.
                    </div>
                </div>
            </div>
        </section>
        <div class="w-full md:w-4/6 my-6 mx-auto h-auto p-4 border border-shark-500 rounded-lg">
            <form method="POST" action="" class="w-full flex flex-col gap-4">
                {% csrf_token %}
                <div class="text-2xl font-semibold text-primary-400 text-center">
                    FORM BUAT UJIAN KUALIFIKASI
                </div>
                <hr class="border-shark-400">
                <section id="daftar-atlet-field" class="flex flex-col gap-4">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Tahun
                        </div>
                        <div>
                            {{buat_ujian_kualifikasi.tahun | addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Batch
                        </div>
                        <div>
                            {{buat_ujian_kualifikasi.batch | addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Tempat Pelaksanaan
                        </div>
                        <div>
                            {{buat_ujian_kualifikasi.tempat_pelaksanaan | addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Tanggal Pelaksanaan
                        </div>
                        <div>
                            {{buat_ujian_kualifikasi.tanggal_pelaksanaan | addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                </section>
                <hr class="border-shark-400">
                <section id="auth-login-submit" class="space-y-1">
                    <button
                        class="bg-primary-500 w-full py-2 rounded-lg hover:bg-primary-400 transition cursor-pointer text-white font-semibold"
                        type="submit" name="buat_ujian_kualifikasi_submit">
                            BUAT
                    </button>
                </section>
            </form>
        </div>
    </div>
</section>

{% endblock content %}
                
               

tes_kualifikasi/templates/data_kualifikasi.html
{% extends 'base.html' %}
{% load static %}
{% load filter %}

{% block meta %}
<title>Babadu | Tes Kualifikasi</title>
{% endblock meta %}

{% block content %}

<section id="authentication" class="h-screen w-full xl:px-20 lg:px-10 sm:px-2 px-4">
    <div class="h-full flex flex-col gap-8 items-center justify-center text-white">
        <section id="b01" class="w-full">
            <div class="max-w-md mx-auto p-4 border border-shark-400 rounded-lg">
                <div class="flex flex-row items-center justify-start gap-4">
                    <div class="font-semibold text-lg p-4 bg-primary-500 rounded-md">
                        B01
                    </div>
                    <div class="text-start text-shark-400">
                        <a href="/">
                            <span
                                class="text-white font-semibold hover:text-primary-500 transition cursor-pointer">Babadu.b01</span>
                        </a>
                        dibuat untuk memenuhi tugas kelompok pada mata kuliah Basis Data.
                    </div>
                </div>
            </div>
        </section>
        <div class="w-full md:w-4/6 my-6 mx-auto h-auto p-4 border border-shark-500 rounded-lg">
            <form method="POST" action="" class="w-full flex flex-col gap-4">
                <div class="text-2xl font-semibold text-primary-400 text-center">
                    FORM DATA KUALIFIKASI
                </div>
                <hr class="border-shark-400">
                <section id="data-kualifikasi-field" class="flex flex-col gap-4">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Nomor Batch
                        </div>
                        <div>
                            {{data_kualifikasi_form.nomor_batch | addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Tempat Pelaksanaan
                        </div>
                        <div>
                            {{data_kualifikasi_form.tempat_pelaksanaan | addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            Tanggal Pelaksanaan
                        </div>
                        <div>
                            {{data_kualifikasi_form.tanggal_pelaksanaan | addclass:"w-full px-4 py-2 border border-shark-500 bg-transparent outline-none focus:border-primary-400 rounded-md transition text-white"}}
                        </div>
                    </div>
                </section>
            </form>
            <section id="auth-login-submit" class="space-y-1 mt-6">
                <a href="{% url 'tes-kualifikasi:pertanyaan' %}">
                    <button
                        class="bg-primary-500 w-full py-2 rounded-lg hover:bg-primary-400 transition cursor-pointer text-white font-semibold"
                        type="submit">
                            DAFTAR
                    </button>
                </a>
            </section>
        </div>
    </div>
</section>

{% endblock content %}

tes_kualifikasi/templates/list_ujian_kualifikasi.html
{% extends 'base.html' %}
{% load static %}
{% load filter %}

{% block meta %}
<title>Babadu | Tes Kualifikasi</title>
{% endblock meta %}

{% block content %}

<section id="authentication" class="h-screen w-full xl:px-20 lg:px-10 sm:px-2 px-4">
    <div class="h-full flex flex-col gap-8 items-center justify-center text-white">
        <section id="b01" class="w-full">
            <div class="max-w-md mx-auto p-4 border border-shark-400 rounded-lg">
                <div class="flex flex-row items-center justify-start gap-4">
                    <div class="font-semibold text-lg p-4 bg-primary-500 rounded-md">
                        B01
                    </div>
                    <div class="text-start text-shark-400">
                        <a href="/">
                            <span
                                class="text-white font-semibold hover:text-primary-500 transition cursor-pointer">Babadu.b01</span>
                        </a>
                        dibuat untuk memenuhi tugas kelompok pada mata kuliah Basis Data.
                    </div>
                </div>
            </div>
        </section>
        <section class="pt-4 border border-shark-400 rounded-lg overflow-hidden flex flex-col w-full">
            <section class="space-y-2">
                <div class="text-xl text-center font-semibold pb-2 text-primary-500">
                    LIST UJIAN KUALIFIKASI
                </div>
                <hr class="border-shark-400">
            </section>
            <table class="min-w-full text-sm font-light text-center" id="tabel-ujian-kualifikasi">
                <thead class="border-b font-medium border-shark-400">
                    <tr>
                        <th scope="col" class="px-6 py-4">Tahun</th>
                        <th scope="col" class="px-6 py-4">Batch</th>
                        <th scope="col" class="px-6 py-4">Tempat Pelaksanaan</th>
                        <th scope="col" class="px-6 py-4">Tanggal Pelaksanaan</th>
                        {% if request.session.is_atlet %}
                            <th scope="col" class="px-6 py-4">Action</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% if list_ujian_kualifikasi %}
                        {% for ujian_kualifikasi in list_ujian_kualifikasi %}
                        <tr class="border-b transition duration-300 ease-in-out hover:bg-shark-700 border-shark-400">
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.tahun }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.batch }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.tempat }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.tanggal }}</td>
                            {% if request.session.is_atlet %}
                                <td class="whitespace-nowrap px-6 py-4">
                                    <a href = "{{ ujian_kualifikasi.tahun }}/{{ ujian_kualifikasi.batch }}/{{ ujian_kualifikasi.tempat_url }}/{{ ujian_kualifikasi.tanggal_url }}" class="hover:text-primary-500 hover:underline transition">
                                        Ikuti
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    {% else %}
                    <tr class="transition duration-300 ease-in-out hover:bg-shark-700 border-shark-400 text-center">
                        <td colspan="6" class="text-center p-4">Tidak ada Ujian Kualifikasi</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </section>
    </div>
</section>

{% endblock content %}

tes_kualifikasi/templates/pertanyaan_kualifikasi.html
{% extends 'base.html' %}
{% load static %}
{% load filter %}

{% block meta %}
<title>Babadu | Tes Kualifikasi</title>
{% endblock meta %}

{% block content %}

<section id="authentication" class="h-screen w-full xl:px-20 lg:px-10 sm:px-2 px-4">
    <div class="h-full flex flex-col items-center justify-center text-white">
        <section id="b01" class="w-full">
            <div class="max-w-md mx-auto p-4 border border-shark-400 rounded-lg">
                <div class="flex flex-row items-center justify-start gap-4">
                    <div class="font-semibold text-lg p-4 bg-primary-500 rounded-md">
                        B01
                    </div>
                    <div class="text-start text-shark-400">
                        <a href="/">
                            <span
                                class="text-white font-semibold hover:text-primary-500 transition cursor-pointer">Babadu.b01</span>
                        </a>
                        dibuat untuk memenuhi tugas kelompok pada mata kuliah Basis Data.
                    </div>
                </div>
            </div>
        </section>
        <div class="w-full md:w-4/6 my-6 mx-auto h-auto py-4 border border-shark-500 rounded-lg">
            <form method="POST" action="" class="w-full flex flex-col gap-4">
                {% csrf_token %}
                <div class="text-2xl font-semibold text-primary-400 text-center">
                    PERTANYAAN KUALIFIKASI
                </div>
                <hr class="border-shark-400">
                <section id="pertanyaan-kualifikasi-field" class="flex flex-col gap-4 h-[45vh] overflow-auto px-4">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            1. The rules for modern badminton were developed in which country during the 19th century?
                        </div>
                        <div>
                            {{pertanyaan_kualifikasi.nomor_satu | addclass:"text-shark-400 pl-2 border-shark-400 accent-primary-500"}}
                        </div>
                    </div>
                    <hr class="border-shark-400">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            2. In a badminton game, the winner is the first one to reach … points.
                        </div>
                        <div>
                            {{pertanyaan_kualifikasi.nomor_dua | addclass:"text-shark-400 pl-2 border-shark-400 accent-primary-500"}}
                        </div>
                    </div>
                    <hr class="border-shark-400">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            3. What is the name of the international governing body for badminton recognised by the International Olympic Committee?
                        </div>
                        <div>
                            {{pertanyaan_kualifikasi.nomor_tiga | addclass:"text-shark-400 pl-2 border-shark-400 accent-primary-500"}}
                        </div>
                    </div>
                    <hr class="border-shark-400">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            4. When does the umpire call the score out loud during a badminton game?
                        </div>
                        <div>
                            {{pertanyaan_kualifikasi.nomor_empat | addclass:"text-shark-400 pl-2 border-shark-400 accent-primary-500"}}
                        </div>
                    </div>
                    <hr class="border-shark-400">
                    <div class="flex flex-col gap-2">
                        <div class="text-white font-semibold">
                            5. Which term is used when a player violates the rules?
                        </div>
                        <div>
                            {{pertanyaan_kualifikasi.nomor_lima | addclass:"text-shark-400 pl-2 border-shark-400 accent-primary-500"}}
                        </div>
                    </div>
                </section>
                <hr class="border-shark-400">
                <section id="auth-login-submit" class="space-y-1 px-4">
                    <button
                        class="bg-primary-500 w-full py-2 rounded-lg hover:bg-primary-400 transition cursor-pointer text-white font-semibold"
                        type="submit" name="pertanyaan_kualifikasi_submit">
                        SUBMIT
                    </button>
                </section>
            </form>
        </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <section class="flex justify-center items-center overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none bg-neutral-800/70">
        <div class="relative w-full md:w-4/6 lg:w-3/6 xl:w-2/5 my-6 mx-auto h-full lg:h-auto md:h-auto">
            <div class="translate h-full lg:h-auto md:h-auto border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-midnight outline-none focus:outline-none">
                <div class="px-8 py-12 flex flex-col gap-4">
                    <div class="text-2xl text-center text-white font-semibold">
                        Ujian Kualifikasi Tidak Dapat Diikuti
                    </div>
                    <hr class="border-shark-400 w-full">
                    <div class="text-center text-danger">
                        {{ message }}
                    </div>
                    <hr class="border-shark-400 w-full">
                    <div>
                        <h1 class="text-shark-200 text-base text-center">
                            Kembali ke list ujian kualifikasi?
                            <a class="text-primary-400 hover:underline transition"
                                href="{% url 'tes-kualifikasi:atlet-list-ujian-kualifikasi' %}">
                                List Ujian Kualifikasi
                            </a>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
    {% endif %}
</section>

<script>

</script>

{% endblock content %}

tes_kualifikasi/templates/riwayat_ujian_kualifikasi.html
{% extends 'base.html' %}
{% load static %}
{% load filter %}

{% block meta %}
<title>Babadu | Tes Kualifikasi</title>
{% endblock meta %}

{% block content %}

<section id="authentication" class="h-screen w-full xl:px-20 lg:px-10 sm:px-2 px-4">
    <div class="h-full flex flex-col gap-8 items-center justify-center text-white">
        <section id="b01" class="w-full">
            <div class="max-w-md mx-auto p-4 border border-shark-400 rounded-lg">
                <div class="flex flex-row items-center justify-start gap-4">
                    <div class="font-semibold text-lg p-4 bg-primary-500 rounded-md">
                        B01
                    </div>
                    <div class="text-start text-shark-400">
                        <a href="/">
                            <span
                                class="text-white font-semibold hover:text-primary-500 transition cursor-pointer">Babadu.b01</span>
                        </a>
                        dibuat untuk memenuhi tugas kelompok pada mata kuliah Basis Data.
                    </div>
                </div>
            </div>
        </section>
        <section class="pt-4 border border-shark-400 rounded-lg overflow-hidden flex flex-col w-full">
            <section class="space-y-2">
                <div class="text-xl text-center font-semibold pb-2 text-primary-500">
                    RIWAYAT UJIAN KUALIFIKASI
                </div>
                <hr class="border-shark-400">
            </section>
            <table class="min-w-full text-sm font-light text-center" id="tabel-ujian-kualifikasi">
                <thead class="border-b font-medium border-shark-400">
                    <tr>
                        {% if request.session.is_umpire %}
                            <th scope="col" class="px-6 py-4">Nama Atlet</th>
                        {% endif %}
                        <th scope="col" class="px-6 py-4">Tahun</th>
                        <th scope="col" class="px-6 py-4">Batch</th>
                        <th scope="col" class="px-6 py-4">Tempat Pelaksanaan</th>
                        <th scope="col" class="px-6 py-4">Tanggal Pelaksanaan</th>
                        <th scope="col" class="px-6 py-4">Hasil</th>
                    </tr>
                </thead>
                <tbody>
                    {% if riwayat_ujian_kualifikasi %}
                        {% for ujian_kualifikasi in riwayat_ujian_kualifikasi %}
                        <tr class="border-b transition duration-300 ease-in-out hover:bg-shark-700 border-shark-400">
                            {% if request.session.is_umpire %}
                                <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.nama }}</td>
                            {% endif %}
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.tahun }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.batch }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.tempat }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.tanggal }}</td>
                            <td class="whitespace-nowrap px-6 py-4">{{ ujian_kualifikasi.hasil_lulus }}</td>
                        </tr>
                        {% endfor %}
                    {% else %}
                    <tr class="transition duration-300 ease-in-out hover:bg-shark-700 border-shark-400 text-center">
                        <td colspan="6" class="text-center p-4">Tidak ada Riwayat Ujian Kualifikasi</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </section>
    </div>
</section>

{% endblock content %}
            